# Generated by Django 3.2.6 on 2022-04-17 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20220417_1324'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_status', models.BooleanField(default=False)),
                ('role', models.ManyToManyField(to='user.Role')),
                ('send_notification_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Send Notification',
                'verbose_name_plural': 'Send Notifications',
            },
        ),
    ]
