# Generated by Django 3.2.6 on 2022-04-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'FeedBack', 'verbose_name_plural': 'FeedBacks'},
        ),
    ]
