# Generated by Django 3.2.6 on 2022-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_paper', '0002_alter_feedback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
