# Generated by Django 3.2.6 on 2022-04-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0002_exampaper_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='paper_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
