# Generated by Django 3.2.6 on 2022-04-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0003_exampaper_paper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
