# Generated by Django 3.2.6 on 2022-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload', '0005_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
