# Generated by Django 4.0.3 on 2022-03-22 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RagisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
                ('roll', models.CharField(blank=True, choices=[('HOD', 'HOD'), ('HOI', 'HOI'), ('SETTER', 'SETTER')], default='SETTER', max_length=25, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('term_condition', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
