# Generated by Django 4.0.3 on 2022-03-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragisteruser',
            name='term_condition',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
